theme: jekyll-theme-minimal
title: AI-LinkUp 2026
description: "Página web del evento AI-LinkUp 2026 de la Universidad de Sonora."
email: ai-linkup@unison.mx

url: https://ai-linkup.github.io

people:
- name: Julio Waissman Vilanova
  position: Colaborador Académico
- name: Samuel González López
  position: Colaborador Académico
- name: Juan Pablo Soto Barrera
  position: Colaborador Académico
- name: Eduardo Acuña Yeomans
  position: Colaborador Académico
- name: Adrián Vázquez Osorio
  position: Colaborador Académico
- name: David Herrera Sánchez
  position: Colaborador Académico
- name: Aaron Lara Ordoñez
  position: Colaborador Académico
- name: Francisco Ricardo Hernandez Astorga
  position: Colaborador Estudiante
- name: Karol Burrola Torres
  position: Colaboradora Estudiante
- name: Sebastian Alcantar Vicencio
  position: Colaborador Estudiante
- name: Kevin Osmar Núñez Manríquez
  position: Colaborador Estudiante
- name: Dania Paloma Vega Noriega
  position: Colaboradora Estudiante

future: true
